[project]
name = "ml-flow-experimentation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dagshub>=0.6.2",
    "matplotlib>=3.10.5",
    "mlflow>=3.1.4",
    "scikit-learn>=1.7.1",
    "seaborn>=0.13.2",
]
